### ISSUE TITLE
Notes imported from Memos cannot be rebuild embedding index.

### ISSUE THREAD

**Issue by eallion** [blinko-space/blinko#184]
**Describe the bug**
Notes imported from Memos cannot be rebuild embedding index.

**To Reproduce**
1. Set AI
2. Import memos_prod.db
3. Rebuild embedding index

**Expected behavior**
Rebuild embedding index

**Screenshots**
![PixPin_2024-11-26_15-53-22](https://github.com/user-attachments/assets/fef2d99d-7f20-419a-b383-cee0215d9235)

**Desktop (please complete the following information):**
 - OS: Docker latest
 - Browser: Chrome & Firefox latest
 - Version: 0.8.8 to 0.8.15

**Smartphone (please complete the following information):**
 - ~Device: [e.g. iPhone6]~
 - ~OS: [e.g. iOS8.1]~
 - ~Browser [e.g. stock browser, safari]~
 - ~Version [e.g. 22]~

**Additional context**
```bash
rebuild index error-> TypeError: i.attachments is not iterable
    at z.rebuildEmbeddingIndex (/app/.next/server/chunks/2746.js:1:14697)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/.next/server/chunks/2746.js:43:14230
    at async file:///app/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:90:30
```

**Comment by eallion** [comment]
❤️
