### ISSUE TITLE
Vercel Deploy: Add a Serverless-Friendly Storage Option to Eliminate Local Filesystem Dependencies

### ISSUE THREAD

**Issue by guoquan** [blinko-space/blinko#299]
**Is your feature request related to a problem? Please describe.**

I’m attempting to deploy Blinko on a serverless platform (Vercel), but it fails due to attempts to write or access local filesystem directories (e.g., /var/task/.blinko, /var/task/prisma/seedfiles) at runtime. Since Vercel’s environment is read-only and does not support persistent writes, these operations trigger ENOENT errors and prevent Blinko from running successfully.

**Describe the solution you'd like**

I’d like Blinko to support a configuration mode that doesn’t rely on runtime filesystem writes. Possible approaches could include:
- Stateless/in-memory mode option: Allow Blinko to operate completely in memory at runtime, eliminating the need for local directories. This would be useful for scenarios where the data is ephemeral or can be re-generated as needed.
- External storage integration: Enable configuration of an external storage backend (e.g., S3 or a database) so that Blinko can store and retrieve indexes and data from a remote service. This approach would keep deployments on serverless platforms fully functional and scalable without local file writes.

**Describe alternatives you've considered**

- Manually patching Blinko code to skip file operations, which is not sustainable or ideal.
- Using non-serverless environments that allow local writes, which defeats the purpose of choosing a serverless platform.
- Attempting to provision some form of ephemeral storage, which is either not supported or very limited on platforms like Vercel.

**Additional context**

Below are excerpts from the Vercel backend logs showing the ENOENT errors when Blinko tries to create directories or read seedfiles:

```
[
  [Error: ENOENT: no such file or directory, lstat '/var/task/prisma/seedfiles'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'lstat',
    path: '/var/task/prisma/seedfiles'
  }
]
```

```
{
  objectStorage: 's3',
  s3AccessKeyId: 'XXXX',
  s3AccessKeySecret: 'XXXX',
  s3Bucket: 'XXXX',
  s3Endpoint: 'https://XXXX',
  aiModelProvider: 'OpenAI',
  aiApiKey: 'XXXX',
  aiModel: 'gpt-4o',
  aiApiEndpoint: 'https://XXXX',
  isUseAI: true,
  embeddingModel: 'text-embedding-3-small'
}

init faiss store [ { pageContent: 'init faiss store', metadata: { id: '0' } } ]

VectorStore error Error: ENOENT: no such file or directory, mkdir '/var/task/.blinko'
    at async Module.mkdir (node:internal/fs/promises:857:10)
    at async FaissStore.save (file:///var/task/node_modules/.pnpm/@langchain+community@0.3.6_@aws-crypto+sha256-js@5.2.0_@aws-sdk+client-s3@3.693.0_@aws-sdk+cr_gjp5ymxomstpnmgkjklfpy5w34/node_modules/@langchain/community/dist/vectorstores/faiss.js:136:9)
    at async m.VectorStore (/var/task/.next/server/chunks/3717.js:93:2038)
    at async l.GetProvider (/var/task/.next/server/chunks/3717.js:3:5742)
    at async T.writing (/var/task/.next/server/chunks/3717.js:3:4862)
    at async /var/task/.next/server/chunks/3717.js:95:8612
    at async file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:90:30 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/var/task/.blinko'
}

Error: ENOENT: no such file or directory, mkdir '/var/task/.blinko'
    at async Module.mkdir (node:internal/fs/promises:857:10)
    at async FaissStore.save (file:///var/task/node_modules/.pnpm/@langchain+community@0.3.6_@aws-crypto+sha256-js@5.2.0_@aws-sdk+client-s3@3.693.0_@aws-sdk+cr_gjp5ymxomstpnmgkjklfpy5w34/node_modules/@langchain/community/dist/vectorstores/faiss.js:136:9)
    at async m.VectorStore (/var/task/.next/server/chunks/3717.js:93:2038)
    at async l.GetProvider (/var/task/.next/server/chunks/3717.js:3:5742)
    at async T.writing (/var/task/.next/server/chunks/3717.js:3:4862)
    at async /var/task/.next/server/chunks/3717.js:95:8612
    at async file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:90:30 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/var/task/.blinko'
}

Something went wrong TRPCError
    at getTRPCErrorFromUnknown (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/error/TRPCError.mjs:35:23)
    at Object.onError (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:389:32)
    at file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:95:35 {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: UnknownCauseError
      at getCauseFromUnknown (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/error/TRPCError.mjs:19:21)
      at new TRPCError (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/error/TRPCError.mjs:47:23)
      at getTRPCErrorFromUnknown (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/error/TRPCError.mjs:35:23)
      at Object.onError (file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:389:32)
      at file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:95:35 {
    error: TRPCError: Error: ENOENT: no such file or directory, mkdir '/var/task/.blinko'
        at /var/task/.next/server/chunks/3717.js:95:8714
        at async file:///var/task/node_modules/.pnpm/@trpc+server@11.0.0-rc.553/node_modules/@trpc/server/dist/unstable-core-do-not-import/stream/jsonl.mjs:90:30 {
      code: 'INTERNAL_SERVER_ERROR',
      [cause]: undefined
    },
    path: [ '0', 'result', 'data' ]
  }
}
```

what essentially cause the error:

```
Error: ENOENT: no such file or directory, mkdir '/var/task/.blinko'
Error: ENOENT: no such file or directory, lstat '/var/task/prisma/seedfiles'
```

Having a filesystem-independent storage mechanism would enable Blinko to run smoothly in serverless environments, allowing it to dynamically build indexes from user content without local write operations. This would make Blinko much more flexible and widely usable.

**Comment by blinko-space** [comment]
不建议部署到Vercel vercel不能写入文件 demo部署到vercel只是作为演示站点
